import {
	AlertCircle,
	AlertTriangle,
	ArrowLeft,
	ArrowRight,
	ArrowRightLeft,
	AtSign,
	Barcode,
	Check,
	CheckCircle,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	CircleDollarSign,
	CreditCard,
	Database,
	DollarSign,
	Edit2,
	Eye,
	EyeOff,
	Filter,
	HelpCircle,
	Info,
	Key,
	Loader2,
	Lock,
	Menu,
	Minus,
	MinusCircle,
	MoreHorizontal,
	MoreVertical,
	Nfc,
	Package,
	Percent,
	Plus,
	PlusCircle,
	Printer,
	RefreshCw,
	Search,
	Settings,
	ShoppingCart,
	Sparkles,
	Star,
	Ticket,
	Trash2,
	User,
	X,
} from "lucide-react";

export const iconMap = {
	search: Search,
	plus: Plus,
	minus: Minus,
	trash: Trash2,
	edit: Edit2,
	settings: Settings,
	check: Check,
	close: X,
	x: X,
	info: Info,
	warning: AlertTriangle,
	danger: AlertCircle,
	success: CheckCircle,
	cart: ShoppingCart,
	user: User,
	key: Key,
	lock: Lock,
	back: ArrowLeft,
	forward: ArrowRight,
	print: Printer,
	refresh: RefreshCw,
	card: CreditCard,
	cash: DollarSign,
	percent: Percent,
	sparkles: Sparkles,
	database: Database,
	plusCircle: PlusCircle,
	minusCircle: MinusCircle,
	help: HelpCircle,
	loading: Loader2,
	chevronDown: ChevronDown,
	chevronUp: ChevronUp,
	chevronLeft: ChevronLeft,
	chevronRight: ChevronRight,
	barcode: Barcode,
	menu: Menu,
	moreVertical: MoreVertical,
	moreHorizontal: MoreHorizontal,
	transfer: ArrowRightLeft,
	credit: CircleDollarSign,
	voucher: Ticket,
	package: Package,
	filter: Filter,
	atSign: AtSign,
	eye: Eye,
	eyeOff: EyeOff,
	star: Star,
	nfc: Nfc,
} as const;

export type IconName = keyof typeof iconMap;
